classe = input("Escolha a classe (guerreiro, mago ou arqueiro):")
forca = int(input("Digite os pontos de força (de 1 a 20):"))
magia = int(input("Digite os pontos de magia (de 1 a 20):"))
Valido = 'mago' and (forca >= 15) and (magia <=10)
'guerreiro' and (forca >= 15) and (magia <= 10)
'arqueiro' and (5 < forca < 15) and (5 < magia < 15)
print("Pontos de atributo consistentes com a classe escolhida:", Valido)